before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - main: ./cmd/unamegen
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    mod_timestamp: "{{ .CommitTimestamp }}"
archives:
  - format_overrides:
      - goos: windows
        format: zip
brews:
  - tap:
      owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
      name: "{{ .ProjectName }}"
    folder: Formula
    commit_msg_template: "build: update formulae to version {{ .Tag }}"
    homepage: "https://github.com/{{ .Env.GITHUB_REPOSITORY }}"
    description: Generate user names with ease
    license: MIT
