before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/unamegen
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    mod_timestamp: "{{ .CommitTimestamp }}"
archives:
  - format_overrides:
      - goos: windows
        format: zip
changelog:
  skip: true
