# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unamegen < Formula
  desc "Generate user names with ease"
  homepage "https://github.com/thde/unamegen"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thde/unamegen/releases/download/v0.3.0/unamegen_0.3.0_darwin_amd64.tar.gz"
      sha256 "f83ee110f04b5caf6df4c454b5784ecd4b33dc9ce78ac147617f67f4497984e9"

      def install
        bin.install "unamegen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thde/unamegen/releases/download/v0.3.0/unamegen_0.3.0_darwin_arm64.tar.gz"
      sha256 "f3ba43fc9c07acbee6c67d86913f9ccc55362c77dfa968d935b74f1b232384b3"

      def install
        bin.install "unamegen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thde/unamegen/releases/download/v0.3.0/unamegen_0.3.0_linux_arm64.tar.gz"
      sha256 "4112fd85ec395dce1b9cd6eaa86aefb43657ad04405a13b7a1e914a415a498f6"

      def install
        bin.install "unamegen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/thde/unamegen/releases/download/v0.3.0/unamegen_0.3.0_linux_amd64.tar.gz"
      sha256 "3f3838f5eacc5a82c33211be3e0612856c5a2cbe9392eb6216bf27360174dd25"

      def install
        bin.install "unamegen"
      end
    end
  end
end
