name: web

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v3
      - name: install tinygo
        run: |
          cd $(mktemp -d)
          curl -sLo tinygo.deb https://github.com/tinygo-org/tinygo/releases/download/v${TINYGO_VERSION}/tinygo_${TINYGO_VERSION}_amd64.deb
          sudo dpkg -i tinygo.deb
        env:
          TINYGO_VERSION: 0.27.0
      - run: make web
      - uses: cloudflare/pages-action@v1
        with:
          directory: public
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ github.event.repository.name }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
